# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IM' do
  use_frameworks!

  pod 'Protobuf', '3.11.4'
  pod 'CocoaAsyncSocket'
  pod 'ReactiveObjC'


  target 'IMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IMUITests' do
    # Pods for testing
  end

end
